const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{
const b=await chromium.launch({headless:true,...(process.env.READING_CHROMIUM?{executablePath:process.env.READING_CHROMIUM}:{})});
try{
const c=await b.newContext({viewport:{width:1440,height:1000}}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
const base=process.env.READING_BASE_URL||'http://127.0.0.1:18002',out=process.env.READING_OUTPUT||'/tmp/fieldtofit-cw1-ui';fs.mkdirSync(out,{recursive:true});
await p.goto(base+'/for-you');await p.locator('.watch-card').last().waitFor();assert.equal(await p.locator('.watch-card').count(),27);assert.equal(await p.locator('.watch-group').count(),5);await p.locator('.news-card').last().waitFor();assert.equal(await p.locator('.news-card').count(),10);
const data=await(await c.request.get(base+'/api/v1/platform/watch')).json();assert.deepEqual(data.groups.map(g=>g.count),[9,4,7,3,4]);
const rpc=async(method,params={})=>{const r=await c.request.post(base+'/api/mcp/curated',{headers:{Accept:'application/json, text/event-stream'},data:{jsonrpc:'2.0',id:1,method,params}});assert.equal(r.status(),200);return(await r.json()).result;};
assert((await rpc('initialize',{protocolVersion:'2025-06-18',capabilities:{},clientInfo:{name:'fieldtofit-watch-acceptance',version:'1'}})).instructions.includes('curated_watch'));assert.equal((await rpc('tools/list')).tools.length,12);assert.deepEqual((await rpc('tools/call',{name:'curated_watch',arguments:{}})).structuredContent,data);
await p.goto(base+'/for-you#watch-cw-m04');await p.waitForFunction(()=>document.querySelector('#watch-cw-m04 details')?.open);assert.equal(await p.evaluate(()=>document.activeElement.id),'watch-cw-m04');assert.match(await p.locator('#watch-cw-m04').textContent(),/K2.7-Code/);assert((await p.locator('#watch-cw-m04').boundingBox()).y>=70);await p.screenshot({path:out+'/desktop-kimi.png'});await p.reload();await p.waitForFunction(()=>document.querySelector('#watch-cw-m04 details')?.open);
const search=async(q)=>{await p.getByRole('textbox',{name:'搜索持续关注',exact:true}).fill(q);await p.locator('.watch-section').getByRole('button',{name:'搜索',exact:true}).click();};
await search('VideoCrop');await p.waitForFunction(()=>document.querySelectorAll('.watch-card').length===1);assert.match(await p.locator('.watch-card').textContent(),/ComfyUI/);await p.locator('.news-card').last().waitFor();assert.equal(await p.locator('.news-card').count(),10);
await search('no-matching-watch');await p.getByText('没有匹配的持续关注资料，可更换关键词或清除筛选。',{exact:true}).waitFor();await p.getByRole('button',{name:'清除全部筛选',exact:true}).click();await p.waitForFunction(()=>document.querySelectorAll('.watch-card').length===27);
await p.getByRole('combobox',{name:'持续关注类型',exact:true}).selectOption('skill');await p.waitForFunction(()=>document.querySelectorAll('.watch-card').length===3);
await p.goto(base+'/for-you#watch-cw-t01');await p.waitForFunction(()=>document.querySelector('#watch-cw-t01 details')?.open);await p.setViewportSize({width:390,height:844});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
const toggle=p.getByRole('button',{name:'本页目录',exact:false}),nav=p.getByRole('navigation',{name:'本页目录'});await toggle.click();await nav.getByRole('link',{name:'Harness · 4',exact:true}).click();assert.equal(await toggle.getAttribute('aria-expanded'),'false');
await p.goto(base+'/for-you#watch-cw-h01');await p.waitForFunction(()=>document.querySelector('#watch-cw-h01 details')?.open);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:out+'/mobile-harness.png'});await toggle.click();await p.keyboard.press('Tab');await p.keyboard.press('Escape');assert.equal(await toggle.getAttribute('aria-expanded'),'false');
await p.goto(base+'/for-your-ai');await p.getByRole('combobox',{name:'查看持续关注资料',exact:true}).selectOption('CW-T01');await p.getByText('查看机器可读资料',{exact:true}).click();assert.match(await p.locator('.watch-ai pre').textContent(),/VideoCrop/);
const [download]=await Promise.all([p.waitForEvent('download'),p.locator('.watch-ai').getByRole('button',{name:'下载此项资料',exact:true}).click()]);await download.saveAs(out+'/download.json');assert.equal(JSON.parse(fs.readFileSync(out+'/download.json')).items[0].id,'CW-T01');
await p.route('**/api/v1/platform/watch*',r=>r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'unavailable'})}));await p.goto(base+'/for-you');await p.getByText('持续关注暂时无法读取。',{exact:true}).waitFor();assert.equal(await p.locator('.watch-card').count(),0);assert.match(await p.locator(".reading-toc").textContent(),/持续关注 · —/);await p.locator('.news-card').last().waitFor();assert.equal(await p.locator('.news-card').count(),10);assert.deepEqual(errors,[]);
fs.writeFileSync(out+'/result.json',JSON.stringify({passed:true,base,revision:data.revision,groups:data.groups,checks:['27 profiles / 5 groups / 10 news','12 MCP tools / identical HTTP data','deep links / reload / focus','search / empty / reset / type','mobile directory / Escape / no overflow','AI preview and download','failure state'],screenshots:['desktop-kimi.png','mobile-harness.png']},null,2));console.log('Continuous-watch browser acceptance passed');
}finally{await b.close();}
})().catch(e=>{console.error(e);process.exit(1)});
