// Run against an isolated server with 25 published QA dossiers; never writes data.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
(async () => {
  const browser = await chromium.launch({headless:true, ...(process.env.READING_CHROMIUM ? {executablePath:process.env.READING_CHROMIUM} : {})});
  const context = await browser.newContext({ viewport:{width:1440,height:1000} });
  const page = await context.newPage(); const errors=[]; page.on('pageerror', e=>errors.push(e.message));
  const base=process.env.READING_BASE_URL || 'http://127.0.0.1:18001';
  const output=process.env.READING_OUTPUT || '/tmp/fieldtofit-reading-ui';fs.mkdirSync(output,{recursive:true});
  await page.goto(base+'/for-you');
  await page.locator('.news-card').last().waitFor();await page.locator('.platform-feed .platform-card').last().waitFor();
  assert.equal(await page.locator('.news-card').count(),10);
  assert.equal(await page.locator('.news-glance li').count(),5);
  assert.equal(await page.locator('.platform-feed .platform-card').count(),20);
  assert.match(await page.locator('.reading-page-summary').textContent(),/25/);
  const nav=page.getByRole('navigation',{name:'本页目录'});
  await nav.getByRole('link',{name:'DeepSeek-V4.1-Flash',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#news-d-10 details')?.open);
  assert.equal(await page.locator('#news-d-10 details').getAttribute('open'),'');
  assert.equal(await page.evaluate(()=>document.activeElement.id),'news-d-10');
  assert((await page.locator('#news-d-10').boundingBox()).y>=70);
  await page.reload();await page.waitForFunction(()=>document.querySelector('#news-d-10 details')?.open);
  await page.screenshot({path:output+'/desktop-news.png'});
  await nav.getByRole('link',{name:/资源档案/}).click();
  await page.getByRole('textbox',{name:'搜索精选对象'}).fill('QA Resource 24');
  await page.getByRole('button',{name:'搜索',exact:true}).click();
  await page.waitForFunction(()=>document.querySelectorAll('.platform-feed .platform-card').length===1);
  assert.equal(await page.locator('.news-card').count(),10);
  assert.match(await nav.textContent(),/当前筛选结果/);
  await page.getByRole('textbox',{name:'搜索精选对象'}).fill('not-in-catalog');await page.getByRole('button',{name:'搜索',exact:true}).click();
  await nav.getByText('没有匹配档案',{exact:true}).waitFor();
  await page.getByRole('button',{name:'清除全部资源筛选'}).click();
  await page.waitForFunction(()=>document.querySelectorAll('.platform-feed .platform-card').length===20);
  const before=await page.locator('.platform-feed article').first().getAttribute('id');
  await page.getByRole('button',{name:'下一页',exact:true}).click();
  await page.waitForFunction(()=>document.querySelectorAll('.platform-feed .platform-card').length===5);
  assert.notEqual(await page.locator('.platform-feed article').first().getAttribute('id'),before);
  assert.equal(await nav.locator('a[href*="#resource-"]').count(),6); // section + five current-page dossiers
  await page.getByRole('button',{name:'上一页',exact:true}).click();
  await page.waitForFunction(()=>document.querySelectorAll('.platform-feed .platform-card').length===20);
  await page.goto(base+'/for-you#news-d-01');await page.waitForFunction(()=>document.querySelector('#news-d-01 details')?.open);
  await page.setViewportSize({width:390,height:844});
  const toggle=page.getByRole('button',{name:'本页目录',exact:false});await toggle.click();
  await nav.getByRole('link',{name:'DeepSeek-V4.1-Flash',exact:true}).click();
  await page.waitForFunction(()=>document.activeElement.id==='news-d-10');
  assert.equal(await toggle.getAttribute('aria-expanded'),'false');
  assert.equal(await page.evaluate(()=>document.activeElement.id),'news-d-10');
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
  await page.screenshot({path:output+'/mobile-news.png'});
  await toggle.click();await page.keyboard.press('Tab');await page.keyboard.press('Escape');
  assert.equal(await toggle.getAttribute('aria-expanded'),'false');assert(await toggle.evaluate(e=>e===document.activeElement));
  await page.goto(base+'/for-your-ai');await page.getByText('curated_news',{exact:true}).waitFor();
  await page.route('**/api/v1/platform/news',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'unavailable'})}));
  await page.goto(base+'/for-you');await page.getByText('动态暂时无法读取。',{exact:true}).waitFor();
  assert.equal(await page.locator('.news-card').count(),0);
  assert.match(await page.locator('.reading-toc').textContent(),/发布与更新 · —/);
  assert.deepEqual(errors,[]);
  fs.writeFileSync(output+'/result.json',JSON.stringify({passed:true,checks:['10 releases / 5 highlights','desktop directory','deep link and reload','focus and expansion','resource filter / empty / reset','25 dossiers / pagination','mobile directory / Escape / no overflow','AI entry','news failure without false zero'],screenshots:['desktop-news.png','mobile-news.png']},null,2));
  await browser.close(); console.log('Reading browser acceptance passed');
})().catch(e=>{console.error(e);process.exit(1)});
