import { codexTypes } from './codexData';
import { CodexSourceEditor } from './CodexSourceEditor';
import { CodexRoundupEditor } from './CodexRoundupEditor';
type Value=Record<string,any>;
export function CodexTopicEditor({value,onChange}:{value:Value|null;onChange:(value:Value|null)=>void}){
 const edit=(key:string,v:unknown)=>onChange({...value,[key]:v});
 const input=(key:string,label:string,type='text')=><label className="management-field"><span>{label}</span><input aria-label={label} type={type} value={value?.[key]??''} onChange={e=>edit(key,e.target.value||null)}/></label>;
 return <details><summary>Codex 28天专题</summary><label className="management-check"><input type="checkbox" checked={!!value} onChange={e=>onChange(e.target.checked?{group:'codex',type:'feature',event_key:'',official_day:null,date_precision:'instant',announced_at:'',timestamp_basis:'official_timestamp'}:null)}/>将已核实的这条动态加入专题</label>{value&&<><p>使用同一份动态及出处。日期仅由带时区的发布时间或明确的来源日期归组；发布前仍须核对预览。撤销勾选并发布即可移出专题，原动态继续保留。</p><label>专题分组<select value={value.group} onChange={e=>onChange({...value,group:e.target.value,official_day:e.target.value==='other_openai'?null:value.official_day})}><option value="codex">Codex／ChatGPT Work</option><option value="other_openai">其他 OpenAI 更新</option></select></label><label>更新类型<select value={value.type} onChange={e=>edit('type',e.target.value)}>{Object.entries(codexTypes).map(([k,v])=><option key={k} value={k}>{v[0]}</option>)}</select></label>{input('event_key','事件标识（公开出处中的官方原帖／版本链接）')}<label className="management-field"><span>官方 Day 编号（官方未给出则留空）</span><input aria-label="官方 Day 编号" type="number" min="1" max="28" disabled={value.group==='other_openai'} value={value.official_day??''} onChange={e=>edit('official_day',e.target.value?Number(e.target.value):null)}/></label><label>日期精度<select value={value.date_precision} onChange={e=>onChange({...value,date_precision:e.target.value,announced_at:null,timestamp_basis:e.target.value==='source_date'?'source_date':'official_timestamp'})}><option value="instant">确切发布时间，换算为北京日期</option><option value="source_date">官方仅给出日期，不推造时刻</option></select></label>{value.date_precision==='instant'?<>{input('announced_at','发布时间（ISO，含 Z 或 +08:00 等时区）')}<label>时间依据<select value={value.timestamp_basis} onChange={e=>edit('timestamp_basis',e.target.value)}><option value="official_timestamp">官方 API 发布时间</option><option value="post_id_derived">原帖 ID 推导，已交叉核对</option></select></label><p>事件日期须与时间换算出的北京日期一致。</p></>:<p>填写上方来源发布日期，并将事件日期留空。</p>}{value.type==='reset'&&<fieldset><legend>已确认生效的额度重置</legend>{[['plans','适用套餐'],['scope','重置范围'],['effective_at','确认生效时间（ISO，含时区）'],['source_url','确认出处（公开来源中已登记）']].map(([key,label])=><label className="management-field" key={key}><span>{label}</span><input aria-label={label} value={value.reset?.[key]||''} onChange={e=>edit('reset',{...value.reset,[key]:e.target.value})}/></label>)}</fieldset>}<CodexSourceEditor value={value} onChange={onChange}/><CodexRoundupEditor value={value} onChange={onChange}/></>}</details>;
}
