import { useEffect, useRef, useState } from 'react';
import { useWorkspace } from './UI';
import { codexTypes, dayItems, monthCells, overview, weekStart, type CodexTopic } from './codexData';
import type { NewsItem } from './NewsReading';
const KEY='fieldtofit-codex-overview-view';
const FULL_KEY='fieldtofit-codex-calendar-full';
type View='month'|'strip';
function preferred():View{try{return localStorage.getItem(KEY)==='strip'?'strip':'month';}catch{return 'month';}}
export function CodexOverview({topic,byId,current,choose,today,catchupEnd,preview}:{topic:CodexTopic;byId:Map<string,NewsItem>;current:string;choose:(date:string)=>void;today:string;catchupEnd:string;preview:boolean}){
 const {pick,zh}=useWorkspace();const [view,setView]=useState<View>(preferred);const [month,setMonth]=useState(()=>current==='all'?topic.days[0].date.slice(0,7):current.slice(0,7));
 const [full,setFull]=useState(()=>{try{return localStorage.getItem(FULL_KEY)==='true';}catch{return false;}});
 const [expanded,setExpanded]=useState<Set<string>>(()=>new Set());const [located,setLocated]=useState('');
 const fullButton=useRef<HTMLButtonElement>(null);const restoreFocus=useRef(false);
 useEffect(()=>{if(restoreFocus.current){restoreFocus.current=false;fullButton.current?.focus();}},[expanded]);
 const firstMonth=topic.start_date.slice(0,7),lastMonth=catchupEnd.slice(0,7);
 useEffect(()=>{if(current!=='all')setMonth(current.slice(0,7));},[current]);
 const changeView=(value:View)=>{setView(value);if(value==='month'&&current!=='all')setMonth(current.slice(0,7));if(!preview)try{localStorage.setItem(KEY,value);}catch{/* Reading remains available without storage. */}};
 const roundupTitle=(date:string)=>{const r=topic.roundups?.find(r=>r.date===date);return r?pick(`官方 Day ${r.official_day} 小结`,`Official Day ${r.official_day} roundup`):'';};
 const logs=new Map(topic.days.map(d=>[d.date,d]));const allItems=topic.days.filter(d=>d.date.startsWith(month)).flatMap(d=>dayItems(d,byId));
 const mainCount=allItems.filter(i=>i.codex_28_days?.group==='codex'&&i.codex_28_days.type!=='reset').length;
 const resets=allItems.filter(i=>i.codex_28_days?.type==='reset').length;const otherCount=allItems.filter(i=>i.codex_28_days?.group==='other_openai').length;
 const stats=[mainCount?`${mainCount}${pick('项Codex更新',' Codex updates')}`:'',resets?`${resets}${pick('次已生效额度重置',' effective usage resets')}`:'',otherCount?`${otherCount}${pick('项其他OpenAI',' other OpenAI updates')}`:''].filter(Boolean).join(' · ');
 const monthTitle=zh?`${month.slice(0,4)}年${Number(month.slice(5))}月`:new Intl.DateTimeFormat('en',{year:'numeric',month:'long',timeZone:'UTC'}).format(new Date(month+'-01T00:00:00Z'));
 const move=(step:number)=>{const date=new Date(month+'-01T00:00:00Z');date.setUTCMonth(date.getUTCMonth()+step);setMonth(date.toISOString().slice(0,7));setExpanded(new Set());setLocated('');};
 const goToday=()=>{setMonth(today.slice(0,7));setExpanded(new Set([weekStart(today)]));setLocated(today);if(logs.has(today))choose(today);};
 const toggleFull=()=>{const next=!full;setFull(next);setExpanded(new Set());setLocated('');if(!preview)try{localStorage.setItem(FULL_KEY,String(next));}catch{/* Optional reading preference. */}};
 const cells=monthCells(month);const weeks=Array.from({length:cells.length/7},(_,i)=>cells.slice(i*7,i*7+7));
 const rows:{weeks:typeof weeks;folded:boolean}[]=[];
 for(const week of weeks){const visible=full||expanded.has(week[0].date)||week.some(c=>logs.has(c.date)||c.date===located);const previous=rows[rows.length-1];if(!visible&&previous?.folded)previous.weeks.push(week);else rows.push({weeks:[week],folded:!visible});}
 const selected=logs.get(current);const groups=new Map<string,typeof topic.days>();
 for(const day of [...topic.days].reverse()){const key=weekStart(day.date);groups.set(key,[...(groups.get(key)||[]),day]);}
 const classes=(items:NewsItem[])=>[items.some(i=>i.codex_28_days?.group==='codex'&&i.codex_28_days.type!=='reset')?'has-update':'',items.some(i=>i.codex_28_days?.type==='reset')?'has-reset':'',items.some(i=>i.codex_28_days?.group==='other_openai')?'has-other':''].filter(Boolean).join(' ');
 return <section className="codex-overview" aria-labelledby="codex-overview-title">
  <header className="codex-overview-heading"><h4 id="codex-overview-title">{pick('28天概览','28-day overview')}</h4><div className="codex-view-toggle" role="group" aria-label={pick('概览视图','Overview view')}>{(['month','strip'] as View[]).map(v=><button type="button" key={v} aria-pressed={view===v} onClick={()=>changeView(v)}>{v==='month'?pick('月历','Month'):pick('日历条','Date strip')}</button>)}</div></header>
  {view==='month'?<div className="codex-month-view"><div className="codex-month-heading"><h5>{monthTitle}</h5><div className="codex-month-controls"><button type="button" onClick={goToday} disabled={today<topic.start_date||today>catchupEnd}>{pick('今天','Today')}</button><button type="button" aria-label={pick('上个月','Previous month')} disabled={month<=firstMonth} onClick={()=>move(-1)}>‹</button><button type="button" aria-label={pick('下个月','Next month')} disabled={month>=lastMonth} onClick={()=>move(1)}>›</button></div></div>{stats&&<p className="codex-month-stats">{pick('本月','This month: ')}{stats}</p>}
   <div className="codex-weekdays" aria-hidden="true">{pick('一,二,三,四,五,六,日','M,T,W,T,F,S,S').split(',').map((label,i)=><span key={i}>{label}</span>)}</div>
   <div className="codex-month-grid" id="codex-calendar-grid" aria-label={monthTitle}>{rows.map(row=>row.folded?<button type="button" className="codex-calendar-fold" key={row.weeks[0][0].date} aria-expanded="false" onClick={()=>{restoreFocus.current=true;setExpanded(previous=>new Set([...previous,...row.weeks.map(w=>w[0].date)]));}}>{row.weeks[0][0].date.slice(5)} — {row.weeks[row.weeks.length-1][6].date.slice(5)} · {pick('展开日期','Show dates')}</button>:row.weeks.map(week=><div className="codex-calendar-week" key={week[0].date}>{week.map(cell=>{const day=logs.get(cell.date);const items=day?dayItems(day,byId):[];const className=['codex-calendar-cell',cell.inMonth?'':'outside-month',cell.date<topic.start_date||cell.date>catchupEnd?'outside-window':'',cell.date===today?'is-today':'',classes(items),day&&!items.length?'has-summary':''].join(' ');const contents=<><time dateTime={cell.date}>{cell.number}</time>{day&&<><span className="codex-cell-summaries">{!items.length&&<span>{roundupTitle(cell.date)}</span>}{items.slice(0,1).map(item=><span key={item.id}>{item.codex_28_days?.group==='other_openai'&&<small>{pick('其他OpenAI · ','Other OpenAI · ')}</small>}{overview(item,zh)}</span>)}{items.length>1&&<small>+{items.length-1}{pick('项',' more')}</small>}</span><span className="codex-cell-dots" aria-hidden="true"><i className="update-dot"/><i className="reset-dot"/><i className="other-dot"/><i className="summary-dot"/></span></>}</>;return day?<button type="button" key={cell.date} className={className} aria-pressed={current===cell.date} aria-label={cell.date+' · '+(items.length?items.map(i=>`${i.codex_28_days?.group==='other_openai'?pick('其他OpenAI','Other OpenAI'):pick(codexTypes[i.codex_28_days!.type][0],codexTypes[i.codex_28_days!.type][1])}：${overview(i,zh)}`).join('；'):roundupTitle(cell.date))} onClick={()=>choose(cell.date)}>{contents}</button>:<div key={cell.date} className={className}>{contents}</div>;})}</div>))}</div>
   <button type="button" className="codex-calendar-full text-button" ref={fullButton} aria-expanded={full} aria-controls="codex-calendar-grid" onClick={toggleFull}>{full?pick('收起空白周','Fold empty weeks'):pick('展开完整月历','Show full month')}</button>
   <div className="codex-calendar-legend"><span><i className="update-dot"/>Codex / Work</span>{resets>0&&<span><i className="reset-dot"/>{pick('已生效重置','Effective reset')}</span>}<span><i className="other-dot"/>{pick('其他OpenAI','Other OpenAI')}</span>{topic.days.some(d=>d.date.startsWith(month)&&!dayItems(d,byId).length)&&<span><i className="summary-dot"/>{pick('官方小结','Official roundup')}</span>}</div>
   {selected&&<p className="codex-selected-summary">{selected.date} · {dayItems(selected,byId).map(i=>overview(i,zh)).join('；')||roundupTitle(selected.date)}</p>}
  </div>:<nav className="codex-strip-view" aria-label={pick('专题日志日期','Progress log dates')}>{[...groups].map(([week,days])=><div key={week}><p className="codex-strip-week">{week}{pick('这一周',' · Week beginning')}</p>{days.map(day=><button type="button" key={day.date} className={'codex-strip-row '+classes(dayItems(day,byId))} aria-pressed={current===day.date} onClick={()=>choose(day.date)}><span><time dateTime={day.date}>{day.date.slice(5).replace('-',' / ')}</time><small>{pick('日历','Calendar')} Day {day.calendar_day}</small></span><span>{!dayItems(day,byId).length&&<span className="codex-strip-summary">{roundupTitle(day.date)}</span>}{dayItems(day,byId).map(item=><span className="codex-strip-summary" key={item.id}><small>{item.codex_28_days?.group==='other_openai'?pick('其他OpenAI','Other OpenAI'):pick(...codexTypes[item.codex_28_days!.type])} · </small>{overview(item,zh)}</span>)}</span></button>)}</div>)}</nav>}
  <button type="button" className="text-button codex-all" aria-pressed={current==='all'} onClick={()=>choose('all')}>{pick('全部日志','All logs')}</button>
 </section>;
}
