import type {MapReading,MapFinding,ReadingBlock} from './MapReportReading';
type Props={value?:MapReading;onChange:(v:MapReading|undefined)=>void;nodes:{id:string;label:string}[];sources:{id:string;title:string}[]};
export function MapReadingEditor({value,onChange,nodes,sources}:Props){
 const change=(i:number,f:Partial<MapFinding>)=>onChange({...value!,findings:value!.findings.map((x,j)=>j===i?{...x,...f}:x)});
 const block=(i:number,j:number,b:Partial<ReadingBlock>)=>change(i,{blocks:value!.findings[i].blocks.map((x,k)=>k===j?{...x,...b}:x)});
 const text=(label:string,v:string|undefined,edit:(s:string)=>void)=><label>{label}<textarea aria-label={label} value={v||''} onChange={e=>edit(e.target.value)}/></label>;
 const evidence=(i:number,j?:number)=>{const f=value!.findings[i],points=j===undefined?f.evidence:f.blocks[j].evidence||[],set=(p:typeof points)=>j===undefined?change(i,{evidence:p}):block(i,j,{evidence:p});return <>{points.map((p,k)=><fieldset key={k}><legend>报告位置 {k+1}</legend><label>报告出处<select aria-label="阅读报告出处" value={p.source_id} onChange={e=>set(points.map((x,n)=>n===k?{...x,source_id:e.target.value}:x))}>{sources.map(s=><option value={s.id} key={s.id}>{s.title}</option>)}</select></label>{text('阅读原文位置',p.locator,s=>set(points.map((x,n)=>n===k?{...x,locator:s}:x)))}{text('阅读原文锚点',p.fragment,s=>set(points.map((x,n)=>n===k?{...x,fragment:s}:x)))}<button type="button" onClick={()=>set(points.filter((_,n)=>n!==k))}>移除位置</button></fieldset>)}<button type="button" onClick={()=>set([...points,{source_id:sources[0]?.id||'',locator:'',fragment:''}])}>添加报告位置</button></>;};
 return <section className="map-reading-editor"><h4>结论与对应论述</h4><label><input type="checkbox" checked={!!value} onChange={e=>onChange(e.target.checked?{title:'报告的核心结论',findings:[],editorial:[]}:undefined)}/>使用图文报告阅读形式</label>{value&&<><p>标题居中；先列编号结论，再按相同编号和标题展开。修改与原图一同进入双端预览和审核发布。</p>{text('报告阅读标题',value.title,s=>onChange({...value,title:s}))}
 {value.findings.map((f,i)=><fieldset key={f.id}><legend>核心观点 {i+1}</legend>{text('核心观点标题',f.title,s=>change(i,{title:s}))}{text('核心观点简述',f.summary,s=>change(i,{summary:s}))}<div>对应路线节点{nodes.map(n=><label key={n.id}><input type="checkbox" checked={f.node_ids.includes(n.id)} onChange={e=>change(i,{node_ids:e.target.checked?[...f.node_ids,n.id]:f.node_ids.filter(x=>x!==n.id)})}/>{n.label}</label>)}</div>{evidence(i)}
 <h5>展开论述</h5>{f.blocks.map((b,j)=><fieldset key={j}><legend>论述块 {j+1}</legend><label>呈现方式<select aria-label="论述呈现方式" value={b.kind} onChange={e=>block(i,j,{kind:e.target.value as ReadingBlock['kind']})}><option value="paragraph">段落</option><option value="points">编号分点</option><option value="highlight">重点标记</option><option value="figure">报告原图</option></select></label>{b.kind==='points'?text('分点内容（每行一点）',b.items?.join('\n'),s=>block(i,j,{items:s.split('\n')})):b.kind==='figure'?<>{(['image_url','alt','caption','attribution','license'] as const).map((k,n)=><div key={k}>{text(['原图资源路径（/report-figures/…png）','原图替代文字（含关键读图信息）','图题与说明','作者与截图署名','复用许可'][n],b[k],s=>block(i,j,{[k]:s}))}</div>)}{evidence(i,j)}</>:<>{text('论述内容',b.text,s=>block(i,j,{text:s}))}{b.kind==='highlight'&&<label>重点性质<select aria-label="重点性质" value={b.label||'claim'} onChange={e=>block(i,j,{label:e.target.value as ReadingBlock['label']})}><option value="claim">作者结论</option><option value="evidence">关键证据</option><option value="limit">适用边界</option></select></label>}</>}
 <button type="button" disabled={j===0} onClick={()=>{const blocks=[...f.blocks];[blocks[j-1],blocks[j]]=[blocks[j],blocks[j-1]];change(i,{blocks});}}>论述块上移</button><button type="button" onClick={()=>change(i,{blocks:f.blocks.filter((_,k)=>k!==j)})}>移除此论述块</button></fieldset>)}<button type="button" onClick={()=>change(i,{blocks:[...f.blocks,{kind:'paragraph',text:''}]})}>添加论述块</button>
 <button type="button" disabled={i===0} onClick={()=>{const findings=[...value.findings];[findings[i-1],findings[i]]=[findings[i],findings[i-1]];onChange({...value,findings});}}>核心观点上移</button><button type="button" onClick={()=>onChange({...value,findings:value.findings.filter((_,j)=>j!==i)})}>移除此核心观点</button></fieldset>)}
 <button type="button" onClick={()=>onChange({...value,findings:[...value.findings,{id:'point-'+crypto.randomUUID().slice(0,8),title:'',summary:'',node_ids:[],evidence:[],blocks:[{kind:'paragraph',text:''}]}]})}>添加核心观点</button>{text('FieldToFit的判断（每行一点）',value.editorial.join('\n'),s=>onChange({...value,editorial:s?s.split('\n'):[]}))}</>}</section>;
}
