import { useState } from 'react';
import { BASE } from '../../api/knowledge';
type Obj=Record<string,any>;
export function MaterialEditor({value,sources,onChange}:{value:Obj[];sources:Obj[];onChange:(v:Obj[])=>void}){
 const [error,setError]=useState(''),[busy,setBusy]=useState(false);
 const update=(i:number,patch:Obj)=>onChange(value.map((m,j)=>j===i?{...m,...patch,...('body' in patch&&!('location_index' in patch)?{location_index:undefined}:{}),approved:false}:m));
 const add=(m:Obj={})=>onChange([...value,{id:'material-'+crypto.randomUUID().slice(0,8),title:m.title||'',url:m.url||'',body:m.body||'',coverage:m.body?'excerpt':'link_only',reason:'公开范围待核对',locator:m.locator||'',retrieved_at:m.retrieved_at||'',upstream_revision:'',checked_at:new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Shanghai'}),rights:{basis:'',url:'',notice:''},approved:false}]);
 return <section><h3>供读者与 AI 读取的材料</h3><p>后台取得的正文默认私密。逐份填写公开依据并复核，随本条内容一同预览、发布；私密备注不要填入公开字段。</p>
 <details><summary>从已存材料加入复核</summary>{sources.map((m,i)=><button className="button" key={i} onClick={()=>add(m)}>{m.title||m.url} · 加入复核</button>)}</details>
 {value.map((m,i)=><fieldset key={i}><legend>材料 {i+1}</legend>{[['id','稳定材料编号'],['title','标题'],['url','原始 URL'],['locator','章节或文件路径'],['upstream_revision','上游版本或提交'],['checked_at','核对日期'],['retrieved_at','获取时间'],['reason','缺失、节选或失效说明']].map(([k,label])=><label key={k}>{label}<input value={m[k]||''} onChange={e=>update(i,{[k]:e.target.value})}/></label>)}<label>可读取范围<select value={m.coverage} onChange={e=>update(i,{coverage:e.target.value,body:['full_text','excerpt'].includes(e.target.value)?m.body:''})}>{[['full_text','全文可读'],['excerpt','部分可读'],['link_only','仅外部链接'],['unavailable','获取失败'],['withdrawn','已失效']].map(([k,n])=><option value={k} key={k}>{n}</option>)}</select></label>{['full_text','excerpt'].includes(m.coverage)&&<><label>导入文字层 PDF（仅整理材料，不发布）<input type="file" accept="application/pdf,.pdf" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);setError('');try{const form=new FormData();form.append('file',file);const response=await fetch(BASE+'/v1/admin/workspace/materials/pdf-extract',{method:'POST',headers:{'X-Admin-Password':sessionStorage.getItem('fieldtofit-admin-password')||''},body:form});const result=await response.json();if(!response.ok)throw new Error(result.detail||'PDF解析失败');update(i,result);}catch(err){setError((err as Error).message);}finally{setBusy(false);e.target.value='';}}}/></label>{m.location_index&&<p>已定位 {m.location_index.pages.length} 个文件页；图像、扫描文字与公式缺口随材料公开。</p>}<label>正文<textarea rows={8} value={m.body} onChange={e=>update(i,{body:e.target.value})}/></label>{[['basis','公开依据（许可证或授权）'],['url','依据链接'],['notice','须随正文保留的许可与署名']].map(([k,n])=><label key={k}>{n}<textarea value={m.rights?.[k]||''} onChange={e=>update(i,{rights:{...m.rights,[k]:e.target.value}})}/></label>)}</>}<label><input type="checkbox" checked={m.approved===true} onChange={e=>onChange(value.map((x,j)=>j===i?{...x,approved:e.target.checked}:x))}/>已核对内容、日期、公开范围和署名</label><button className="text-button" onClick={()=>onChange(value.filter((_,j)=>j!==i))}>移除此材料</button></fieldset>)}
 {error&&<p role="alert">{error}</p>}<button className="button" onClick={()=>add()}>添加材料或缺失记录</button></section>;
}
