import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useRemote, send } from '../../api/knowledge';
import { useWorkspace } from './UI';
import './source-catalog.css';
type Channel={id:string;name:string;url:string;scope:string;company:string;mode:string;enabled:boolean;daily_scheduled:boolean;last_success_at:string|null;last_attempt_at:string|null;state:string;last_run_status:string;access:string;error?:string};
type Organization={id:string;name:string;products:string[];official_url:string;tracking:string[];channels:Channel[];planned:string[];registered_count:number;successful_count:number;published:{id:string;name:string;kind:string}[]};
type Catalog={tracked:Organization[];channels:Channel[];schedule:string;observed_at:string};
export function SourceCatalog({admin=false}:{admin?:boolean}){
 const {pick}=useWorkspace();const data=useRemote<Catalog>(admin?'/v1/admin/workspace/source-catalog':'/v1/platform/source-catalog',admin);
 const [legacy,setLegacy]=useState(false),[busy,setBusy]=useState(''),[error,setError]=useState('');
 const date=(value:string|null)=>value?new Date(value).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'}):pick('尚无成功记录','No successful check');
 const status=(c:Channel)=>!c.enabled?pick('已暂停','Paused'):!c.daily_scheduled?pick('未纳入正式日采集','Outside daily collection'):c.last_run_status==='running'?pick('检查中','Checking'):['error','failed','partial'].includes(c.last_run_status)?pick('需要处理：有失败或未完成项','Attention: failed or unfinished'):!c.last_success_at?pick('已接入，待首次成功','Connected; awaiting success'):c.state==='stale'?pick('检查已逾期','Check overdue'):pick('最近检查成功','Last check succeeded');
 async function act(c:Channel,run=false){setBusy(c.id);setError('');try{await send('/v1/admin/sources/'+encodeURIComponent(c.id)+(run?'/run':''),run?{}:{enabled:!c.enabled},run?'POST':'PATCH',true);data.reload();}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 const channels=data.data?.channels.filter(c=>legacy||c.daily_scheduled||c.company||c.mode==='platform_repository')||[];
 return <div className="source-catalog"><header className="platform-hero"><p className="platform-eyebrow">SOURCES · COVERAGE</p><h1>{pick('关注谁，从哪里发现。','Who we follow. Where we discover.')}</h1><p className="platform-lead">{pick('重点对象和发现渠道共用真实来源配置。已接入、已采集和已发布分别展示；每 1 天检查，有值得发布的内容再整理审核。','Tracked organizations and discovery channels share actual configuration. Connection, collection and publication are separate; sources are checked daily and content is reviewed before publication.')}</p><p className="muted">{admin?pick('计划采集时间：北京时间 06:30；本地 07:30 准备，08:00 交付。实际是否完成，请查看成功时间和异常状态。','Scheduled collection: 06:30 Beijing time; local preparation at 07:30, delivery at 08:00. Check actual completion below.'):pick('计划每天北京时间 06:30 开始检查。实际覆盖和完成情况以各入口的记录为准。','Checks are scheduled to start daily at 06:30 Beijing time. Each endpoint shows actual coverage and completion.')}</p></header>
 {data.loading&&<p role="status">{pick('正在读取来源覆盖…','Loading coverage…')}</p>}{(error||data.error)&&<p role="alert" className="error-text">{error||data.error}</p>}<button className="button" onClick={data.reload}>{pick('刷新状态','Refresh')}</button>
 <section className="platform-panel"><h2>{pick('重点跟踪对象','Organizations we follow')}</h2><p>{pick('公司在名单中不等于全部产品已覆盖。展开公司可查看每个实际入口及待接入范围。','Being listed does not mean every product is covered. Expand an organization to see connected endpoints and missing coverage.')}</p><div className="catalog-table-scroll" tabIndex={0} role="region" aria-label={pick('重点跟踪对象表','Tracked organizations table')}><table><thead><tr>{[pick('公司／团队','Organization'),pick('重点关注对象','Products'),pick('接入与检查情况','Connection and checks'),pick('网站已有内容','Published content')].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{data.data?.tracked.map(o=><tr key={o.id}><td><a href={o.official_url} target="_blank" rel="noreferrer">{o.name} ↗</a></td><td>{o.products.join(' · ')}<small>{o.tracking.join(' · ')}</small></td><td><details><summary>{pick(`${o.registered_count} 个已接入入口 · ${o.successful_count} 个有成功记录`,`${o.registered_count} connected · ${o.successful_count} with successful checks`)}</summary><ul>{o.channels.map(c=><li key={c.id}><a href={c.url} target="_blank" rel="noreferrer">{c.name}</a><small>{c.scope}</small><small>{status(c)} · {date(c.last_success_at)}</small></li>)}</ul>{o.planned.map(p=><p className="muted" key={p}>{p}</p>)}</details></td><td>{o.published.length?o.published.map(p=><Link className="catalog-published" key={p.kind+p.id} to={'/for-you#'+(p.kind==='news'?'news-':'watch-')+p.id.toLowerCase()}>{p.name}</Link>):<span className="muted">{pick('尚无关联的已发布内容','No linked published content')}</span>}</td></tr>)}</tbody></table></div></section>
 <section className="platform-panel"><h2>{pick('发现与采集渠道','Discovery and collection channels')}</h2><label className="catalog-option"><input type="checkbox" checked={legacy} onChange={e=>setLegacy(e.target.checked)}/>{pick('同时查看兼容来源与未调度配置','Include legacy and unscheduled sources')}</label><div className="catalog-table-scroll" tabIndex={0} role="region" aria-label={pick('发现与采集渠道表','Discovery channels table')}><table><thead><tr>{[pick('渠道','Channel'),pick('实际采集范围','Actual scope'),pick('状态与更新','Status and checks'),pick('访问与材料范围','Access and coverage'),...(admin?[pick('操作','Actions')]:[])].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{channels.map(c=><tr key={c.id}><td><a href={c.url} target="_blank" rel="noreferrer">{c.name} ↗</a><small>{{document:'官方页面变化',qwen:'官方研究接口',hub:'模型卡',feed:'官方订阅',index:'官方文章列表',github:'公开仓库发现',hn:'社区讨论',arxiv:'论文摘要',platform_repository:'已维护仓库'}[c.mode]||'兼容来源'}</small></td><td>{c.scope}</td><td><span className={'catalog-state '+(['error','failed','partial'].includes(c.last_run_status)?'attention':'')}>{status(c)}</span><small>{pick('最近成功：','Last success: ')}{date(c.last_success_at)}</small><small>{pick('检查周期：1 天','Check interval: 1 day')}</small>{admin&&c.error&&<p className="error-text">{c.error}</p>}</td><td>{c.access}</td>{admin&&<td><button className="button" disabled={!!busy} onClick={()=>act(c)}>{c.enabled?'暂停':'启用'}</button><button className="button" disabled={!!busy||!c.enabled} onClick={()=>act(c,true)}>{busy===c.id?'处理中…':'立即检查'}</button></td>}</tr>)}</tbody></table></div><p className="muted">{pick('一次来源检查成功，不代表该来源所有文章或模型都已获取；采集结果不会自动进入公开网站。','A successful source check does not mean every article or model was fetched. Collected candidates are not automatically published.')}</p></section></div>;
}
