import { useState } from 'react';
import { send, useRemote } from '../../api/knowledge';
import { NewsReading } from './NewsReading';
import { ContinuousWatch } from './ContinuousWatch';
import './stewardship.css';
type Obj=Record<string,any>;
const root='/v1/admin/workspace/stewardship';
const names:Record<string,string>={name:'名称',organization:'发布方',title:'标题',summary:'摘要',introduction:'介绍',type:'类型',event_date:'事件日期',source_published_at:'来源发布日期',note:'说明',editor:'整理者',attention:'关注信息',origin:'来源类型',submission:'投稿信息',submission_review:'投稿审核信息'};
export function Stewardship({open}:{open:(kind:string,id:string)=>void}){
 const result=useRemote<Obj>(root,true);const [form,setForm]=useState<Obj>({action:'merge',source:'',target:'',choices:{},reason:'',relation:'related',version:'',evidence:'',target_name:'',target_url:'',node_type:'object',restore_target:false});
 const [preview,setPreview]=useState<Obj|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[confirmed,setConfirmed]=useState(false),[mode,setMode]=useState('person');
 const change=(key:string,value:unknown)=>{setForm(f=>({...f,[key]:value}));setPreview(null);setConfirmed(false);setNotice('');};
 const act=async(action:string,payload:Obj)=>{setBusy(true);setError('');try{const response=await send<Obj>(root+'/'+action,payload,'POST',true);if(action==='preview'){setPreview(response);setConfirmed(false);}else{setPreview(null);setConfirmed(false);result.reload();setNotice(action==='check'?'已记录材料访问检查；没有发布或修改正文。':action==='apply'&&['group','separate'].includes(form.action)?'已记录私密整理操作，公开内容未改变。':'操作已记录，请查看最新内容与历史。');}}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const objects=result.data?.items||[];
 const choose=(side:string)=> <label>{side==='source'?'待归并 / 关联对象':'保留 / 关联到'}<select aria-label={side==='source'?'待归并对象':'保留对象'} value={form[side]} onChange={e=>change(side,e.target.value)}><option value="">{side==='target'&&form.action==='relation'?'外部公司、系列或版本':'请选择'}</option>{objects.map((i:Obj)=><option key={i.id} value={i.id}>{i.name} · {i.id} · {i.state==='published'?'已发布':i.state==='withdrawn'?'已撤下':'草稿'}</option>)}</select></label>;
 return <section className="stewardship"><h2>对象归并与材料维护</h2><p>先核对是否同一对象或同一事件。归并和关系需要预览确认；材料访问检查不会自动发布。</p>
 {(error||result.error)&&<p role="alert">{error||result.error}</p>}{notice&&<p role="status">{notice}</p>}
 {(result.error||result.data?.available===false)&&<button className="button" onClick={()=>act('upgrade',{})}>初始化维护记录并重试</button>}
 <details><summary>可能重复或相关 · {result.data?.suggestions?.length??'—'}</summary>{result.data?.suggestions?.map((s:Obj)=><article key={s.source+s.target}><strong>{s.source_name} ↔ {s.target_name}</strong><ul>{s.reasons.map((r:string)=><li key={r}>{r}</li>)}</ul><p>{s.suggestion}</p><button className="button" onClick={()=>{setForm(f=>({...f,source:s.source,target:s.target,action:'merge',choices:{}}));setPreview(null);setConfirmed(false);}}>核对这一组</button></article>)}</details>
 <div className="steward-grid"><label>操作<select value={form.action} onChange={e=>change('action',e.target.value)}><option value="group">归入已有对象的待整理稿（不发布）</option><option value="merge">归并为同一对象 / 事件</option><option value="relation">仅建立有依据的关联</option><option value="separate">保持独立</option>{form.link_id&&<option value="relation_remove">移除所选关联</option>}{form.merge_id&&<option value="undo">撤销所选归并</option>}</select></label>{choose('source')}{choose('target')}</div>
 {form.action==='relation'&&<div className="steward-grid"><label>关系类型<select value={form.relation} onChange={e=>change('relation',e.target.value)}>{[['publisher','发布方'],['family','所属系列'],['version','版本'],['release','发布与更新'],['implementation','官方实现'],['integration','集成关系'],['related','相关资料']].map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><label>适用版本（未知可留空）<input value={form.version} onChange={e=>change('version',e.target.value)}/></label><label>关系依据（官方公开链接）<input value={form.evidence} onChange={e=>change('evidence',e.target.value)}/></label>{!form.target&&<><label>目标类型<select value={form.node_type} onChange={e=>change('node_type',e.target.value)}>{[['company','公司 / 团队'],['family','产品系列'],['version','版本'],['object','外部项目']].map(([v,n])=><option value={v} key={v}>{n}</option>)}</select></label><label>目标名称<input value={form.target_name} onChange={e=>change('target_name',e.target.value)}/></label><label>目标官方入口<input value={form.target_url} onChange={e=>change('target_url',e.target.value)}/></label></>}</div>}
 {form.action==='undo'&&<label><input type="checkbox" checked={form.restore_target} onChange={e=>change('restore_target',e.target.checked)}/>同时恢复目标归并前内容（有后续编辑时禁止覆盖）</label>}
 <label>本次操作说明<textarea aria-label="本次操作说明" value={form.reason} onChange={e=>change('reason',e.target.value)}/></label>
 <button className="button" disabled={busy||!form.source||!form.reason.trim()} onClick={()=>act('preview',form)}>预览影响与冲突</button>
 {preview&&<section className="steward-preview"><h3>归并 / 关联预览</h3>{preview.conflicts?.map((c:Obj)=><div className="steward-conflict" key={c.field}><strong>{names[c.field]||c.field}</strong><p>来源：{typeof c.source==='object'?JSON.stringify(c.source):String(c.source??'未知')}</p><p>保留对象：{typeof c.target==='object'?JSON.stringify(c.target):String(c.target??'未知')}</p><select aria-label={'选择'+(names[c.field]||c.field)} value={form.choices[c.field]||''} onChange={e=>{setForm(f=>({...f,choices:{...f.choices,[c.field]:e.target.value}}));setPreview(p=>p?{...p,ready:false}:p);setConfirmed(false);}}><option value="">逐项确认</option><option value="source">采用来源字段</option><option value="target">采用保留对象字段</option></select></div>)}
 {preview.errors?.map((e:string)=><p role="alert" key={e}>{e}</p>)}{preview.extra?.target_has_later_edits&&<p>目标在归并后已有编辑。撤销将保留其当前内容，只恢复原来源条目；不会覆盖后续工作。</p>}
 {preview.extra?.draft_summary&&<div><h4>待整理稿内容</h4><p>{preview.extra.draft_summary.name} · {preview.extra.draft_summary.summary||preview.extra.draft_summary.introduction}</p><p>阅读材料 {preview.extra.material_count} 份；保存后进入内容库继续整理和审核。</p>{preview.extra.publication_blocker&&<p>{preview.extra.publication_blocker}</p>}<ul>{preview.extra.draft_summary.sources?.map((s:Obj)=><li key={s.url}><a href={s.url} target="_blank" rel="noreferrer">{s.title}</a></li>)}</ul></div>}
 <p>来源编号：{preview.source} → 保留编号：{preview.target||'不变'}。原始材料与历史记录保留。</p>
 <div className="platform-actions"><button className="button" onClick={()=>setMode('person')}>For you 预览</button><button className="button" onClick={()=>setMode('ai')}>For your AI 数据</button></div>
 {mode==='ai'?<pre>{JSON.stringify({action:preview.action,source:preview.source,target:preview.target,relationships:preview.extra,items:preview.preview},null,2)}</pre>:<>{preview.preview?.some((i:Obj)=>i.id.startsWith('D-'))&&<NewsReading data={{schema_version:'',revision:'private-preview',edition:'预览',title:'预览',reviewed_at:'',total:preview.preview.length,items:preview.preview.filter((i:Obj)=>i.id.startsWith('D-'))} as any} loading={false} error="" reload={()=>{}} previewBodies={{}}/>}{preview.preview?.some((i:Obj)=>i.id.startsWith('CW-'))&&<ContinuousWatch result={{data:{schema_version:'',revision:'private-preview',edition:'',reviewed_at:'',scope:'私密预览',total:preview.preview.length,collection_total:preview.preview.length,groups:['model','tool','agent','skill','harness'].map(id=>({id,name:id,count:preview.preview.filter((i:Obj)=>i.type===id).length})),items:preview.preview.filter((i:Obj)=>i.id.startsWith('CW-'))} as any,loading:false,error:'',reload:()=>{}}} previewBodies={{}}/>}{form.action==='relation'&&<p>{preview.source} → {preview.extra.relation} → {preview.extra.target_name} · {preview.extra.version||'未限定版本'} · <a href={preview.extra.evidence} target="_blank" rel="noreferrer">核对关系依据</a></p>}</>}
 <label><input type="checkbox" checked={confirmed} disabled={!preview.ready} onChange={e=>setConfirmed(e.target.checked)}/>已核对冲突、关系依据和公开影响</label><button className="button primary" disabled={busy||!preview.ready||!confirmed} onClick={()=>act('apply',{...form,review_token:preview.review_token,confirmed:true})}>{form.action==='separate'?'确认保持独立':form.action==='group'?'确认归入待整理稿（不发布）':'确认应用到网站与 AI 输出'}</button></section>}
 <details><summary>已确认的关系 · {result.data?.links?.length??'—'}</summary>{result.data?.links?.map((l:Obj)=><p key={l.id}>{l.source_id} → {l.target_id} <button className="text-button" onClick={()=>{setForm(f=>({...f,action:'relation_remove',source:l.source_id,target:'',link_id:l.id,reason:''}));setPreview(null);setConfirmed(false);}}>预览移除此关联</button></p>)}</details><h3>材料持续维护</h3><button className="button" disabled={busy} onClick={()=>act('check',{})}>检查待检材料（最多 25 秒）</button><p>每天检查 1 次；连续 3 个自然日失败进入复核，7 天提升优先级。状态变化不等于新正文发布。</p>
 {result.data?.issues?.length===0&&<p>当前没有到期的材料复核事项；不代表所有材料都已检查。</p>}
 {result.data?.issues?.map((i:Obj)=><MaterialIssue key={i.object_id+i.material_id} item={i} busy={busy} act={act} open={open}/>)}
 <details><summary>归并与维护历史</summary>{result.data?.actions?.map((a:Obj)=><article key={a.id}><strong>{a.action} · {a.source_id}{a.target_id?' → '+a.target_id:''}</strong><p>{a.reason} · {a.created_at}</p>{a.action==='merge'&&!a.undone_at&&<button className="button" onClick={()=>{setForm(f=>({...f,action:'undo',source:a.source_id,target:a.target_id,merge_id:a.id,restore_target:false,reason:'',choices:{}}));setPreview(null);setConfirmed(false);}}>预览撤销此归并</button>}{a.undone_at&&<p>已撤销 · {a.undone_at}</p>}</article>)}</details>
 </section>;
}
function MaterialIssue({item:i,busy,act,open}:{item:Obj;busy:boolean;act:(a:string,p:Obj)=>Promise<void>;open:(k:string,id:string)=>void}){
 const [reason,setReason]=useState(''),[after,setAfter]=useState('');
 return <article className="steward-issue"><h4>{i.name} · {i.material_id}</h4><p>{i.changed?'材料内容或地址有变化':`连续 ${i.failure_days} 个自然日无法访问`} · {i.review_priority===0?'优先复核':'需要复核'}</p><a href={i.url} target="_blank" rel="noreferrer">检查原始入口 ↗</a><p>最后成功：{i.last_success_at||'没有记录'} · 原因：{i.error||'需核对变化'}</p><p>同一材料关联：{i.affected_objects.join('、')}</p>{i.affected_points?.length>0?<ul>{i.affected_points.map((p:Obj,n:number)=><li key={n}>明确引用：{p.title} · {p.locator}</li>)}</ul>:<p>尚无逐观点的明确来源映射，请在内容库核对相关表述；不能把对象关联当作事实定位。</p>}<details><summary>其他可核对材料（不代表可替代该证据）</summary>{i.materials.map((m:Obj)=><p key={m.id}><a href={m.url}>{m.title}</a> · {m.coverage} · {m.checked_at}</p>)}</details><div className="platform-actions"><button className="button" onClick={()=>open(i.object_id.startsWith('D-')?'news':'watch',i.object_id)}>补材料 / 修订 / 退出展示</button><button className="button" disabled={busy} onClick={()=>act('check',{id:i.object_id})}>重新检查</button></div><label>处理说明（保留 / 复核时公开）<textarea aria-label="处理说明（保留 / 复核时公开）" value={reason} onChange={e=>setReason(e.target.value)}/></label><label>延期复查日期<input type="date" value={after} onChange={e=>setAfter(e.target.value)}/></label><div className="platform-actions">{[['retain','保留并说明'],['reviewed','已核对当前材料'],['defer','延期复查']].map(([decision,label])=><button className="button" key={decision} disabled={busy||!reason.trim()||(decision==='defer'&&!after)} onClick={()=>act('decide-material',{id:i.object_id,material_id:i.material_id,decision,reason,review_after:after,check_revision:i.check_revision})}>{label}</button>)}</div></article>;
}
