import {PageMetadata} from '../../search';
import {useEffect,useState,useId} from 'react';
import {Link,useParams} from 'react-router-dom';
import {useRemote} from '../../api/knowledge';
import {SourceLink,useWorkspace} from './UI';
import type {NewsItem} from './NewsReading';
import './technical-maps.css';
import {MapReportReading,mapThumbnail,argumentId} from './MapReportReading';
import type {MapReading} from './MapReportReading';
export type MapEvidence={source_id:string;locator:string;fragment?:string};
export type MapNode={id:string;label:string;kind:'baseline'|'method'|'result';stage:number;mechanism:string;setting:string;result:string;limitation:string;evidence:MapEvidence[];metrics?:{label:string;value:number;unit:string;baseline:string;conditions:string}[]};
export type TechnicalMap={reading?:MapReading;slug:string;question:string;focus:string;takeaway:string;caution:string;change_summary:string;reports:{source_id:string;version:string;first_published_at:string;revised_at?:string|null;substantive_revision:boolean;revision_note:string}[];nodes:MapNode[];edges:{from:string;to:string;relation:'inheritance'|'baseline'|'parallel';label:string;evidence:MapEvidence[]}[]};
export type PublicMap=TechnicalMap & {id:string;title:string;summary:string;sources:NewsItem['sources'];related:NewsItem['related'];publication:NewsItem['publication'];revision:string;archived:boolean;report_activity_at:string;path:string;evidence_scope:string};
type Maps={items:PublicMap[];revision:string;total:number};
const publicationTime=(value?:string|null)=>value?new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(value)):'';
const relations={inheritance:['方法继承／纳入','Inheritance / integration'],baseline:['基线对比','Baseline comparison'],parallel:['并行探索','Parallel exploration']} as const;
function Evidence({points,sources}:{points:MapEvidence[];sources:NewsItem['sources']}){return <ul className="map-evidence">{points.map((e,i)=>{const source=sources.find(s=>s.id===e.source_id);return source&&<li key={i}><SourceLink url={source.url.split('#')[0]+(e.fragment?'#'+e.fragment:'')}>{source.title} · {e.locator}</SourceLink></li>;})}</ul>;}
export function MapGraph({map,sources,onSelect,readingPrefix='',selectedId}:{map:TechnicalMap;sources:NewsItem['sources'];onSelect?:(id:string)=>void;readingPrefix?:string;selectedId?:string}){
 const evidenceId=useId();const {pick}=useWorkspace();const [selected,setSelected]=useState(map.nodes.find(n=>n.kind==='method')?.id||map.nodes[0]?.id||'');
 useEffect(()=>{setSelected(map.nodes.find(n=>n.kind==='method')?.id||map.nodes[0]?.id||'');},[map.slug]);
 const current=map.nodes.find(n=>n.id===(selectedId||selected))||map.nodes[0];const stages=[...new Set(map.nodes.map(n=>n.stage))].sort((a,b)=>a-b);
 const rows=Math.max(...stages.map(s=>map.nodes.filter(n=>n.stage===s).length));const width=Math.max(720,stages.length*250),height=Math.max(300,rows*130+50);
 const positions=Object.fromEntries(map.nodes.map(n=>{const group=map.nodes.filter(x=>x.stage===n.stage),i=group.findIndex(x=>x.id===n.id);return [n.id,{x:stages.indexOf(n.stage)*250+25,y:(height-rows*130)/2+(rows-group.length)*65+i*130}];}));
 return <><div className="map-legend">{Object.entries(relations).map(([key,label])=><span key={key} className={'map-line-label '+key}>{pick(label[0],label[1])}</span>)}</div><p className="muted">{pick('选择节点，查看机制、实验条件与原文。关系的含义见下方列表。','Select a node for mechanisms, experimental conditions and citations. Relationships are listed below.')}</p>
 <p className="map-graph-hint muted">{pick('左右滑动查看完整路线；选择节点后，解释显示在图下。','Scroll horizontally for the full route. Select a node for details below.')}</p><div className="map-graph-scroll"><div className="map-graph" style={{width,height}}><svg width={width} height={height} aria-hidden="true">{map.edges.map((e,i)=>{const a=positions[e.from],b=positions[e.to];const forward=b.x>a.x;return <path key={i} className={'map-edge '+e.relation+(e.from===current?.id||e.to===current?.id?' selected':'')} d={forward?`M ${a.x+200} ${a.y+48} C ${a.x+230} ${a.y+48}, ${b.x-30} ${b.y+48}, ${b.x} ${b.y+48}`:`M ${a.x+100} ${a.y+98} Q ${a.x+235} ${(a.y+b.y)/2+48}, ${b.x+100} ${b.y}`}/>;})}</svg>
 {map.nodes.map(n=><button key={n.id} className={'map-node '+n.kind} style={{left:positions[n.id].x,top:positions[n.id].y}} aria-pressed={current?.id===n.id} aria-controls={evidenceId} onClick={()=>{setSelected(n.id);onSelect?.(n.id);}}><small>{pick(n.kind==='method'?'方法':n.kind==='baseline'?'比较基线':'组合结果',n.kind)}</small><strong>{n.label}</strong>{n.metrics?.[0]&&<span>{n.metrics[0].value} {n.metrics[0].unit}</span>}</button>)}</div></div>
 {current&&<section id={evidenceId} className="map-node-detail" aria-live="polite"><h2>{current.label}</h2><dl>{([['mechanism','机制','Mechanism'],['setting','条件／配置','Conditions / configuration'],['result','报告结果','Reported result'],['limitation','局限','Limitations']] as const).filter(([key])=>!map.reading||key==='mechanism'||key==='result').map(([key,zh,en])=><div key={key}><dt>{pick(zh,en)}</dt><dd>{current[key]}</dd></div>)}</dl>{map.reading?<details className="map-node-full"><summary>{pick('实验条件、完整指标与局限','Experimental conditions, metrics and limits')}</summary><p><strong>{pick('条件／配置：','Conditions: ')}</strong>{current.setting}</p><p><strong>{pick('局限：','Limitations: ')}</strong>{current.limitation}</p>{current.metrics?.map((m,i)=><p className="map-metric" key={i}><strong>{m.label}：{m.value} {m.unit}</strong><span>{pick('比较基线：','Baseline: ')}{m.baseline} · {m.conditions}</span></p>)}</details>:current.metrics?.map((m,i)=><p className="map-metric" key={i}><strong>{m.label}：{m.value} {m.unit}</strong><span>{pick('比较基线：','Baseline: ')}{m.baseline} · {m.conditions}</span></p>)}<Evidence points={current.evidence} sources={sources}/>{map.reading&&<div className="map-node-reading-links">{map.reading.findings.filter(f=>f.node_ids.includes(current.id)).map(f=><a key={f.id} href={'#'+readingPrefix+argumentId(f.id)}>{pick('阅读对应论述：','Read the argument: ')}{f.title} →</a>)}</div>}</section>}
 <details className="map-relations"><summary>{pick('查看全部关系与依据','All relationships and evidence')} · {map.edges.length}</summary>{map.edges.map((e,i)=><article key={i}><h3>{map.nodes.find(n=>n.id===e.from)?.label} → {map.nodes.find(n=>n.id===e.to)?.label}</h3><p>{pick(relations[e.relation][0],relations[e.relation][1])} · {e.label}</p><Evidence points={e.evidence} sources={sources}/></article>)}</details></>;
}
export function MapCards({items,preview=false}:{items:NewsItem[];preview?:boolean}){
 const {pick}=useWorkspace();
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 const recent=(n:NewsItem)=>n.technical_map!.reports.some(r=>{const day=r.substantive_revision?r.revised_at:r.first_published_at;return !!day&&(Date.parse(today+'T00:00:00Z')-Date.parse(day+'T00:00:00Z'))/86400000<30;});
 const all=items.filter(n=>n.technical_map);
 const maps=all.filter(n=>preview||recent(n)).sort((a,b)=>(b.publication?.updated_at||b.source_published_at||'').localeCompare(a.publication?.updated_at||a.source_published_at||''));
 if(!all.length)return null;
 return <section className="technical-maps"><div className="platform-section-heading"><h3 id="technical-evolution-maps" tabIndex={-1}>{pick('技术报告精选&分析','Selected Technical Reports & Analysis')}</h3>{!preview&&<Link to="/maps">{pick('全部精选与历史索引','All reports and history')} →</Link>}</div><p>{pick('精选原始报告，读懂核心结论、证据和适用边界。','Read selected original reports for their core findings, evidence and limits.')}</p>{!maps.length&&<p>{pick('近期暂无新报告，已有问题可在历史索引继续阅读。','No recent reports; existing topics remain in the historical index.')}</p>}<div className="map-cards">{maps.slice(0,3).map(item=>{const map=item.technical_map!;return <article key={item.id}>{mapThumbnail(map)&&(preview?<div className="map-card-figure"><img width="778" height="447" src={mapThumbnail(map)!.image_url} alt={mapThumbnail(map)!.alt} loading="lazy"/></div>:<Link to={'/maps/'+map.slug} className="map-card-figure"><img width="778" height="447" src={mapThumbnail(map)!.image_url} alt={mapThumbnail(map)!.alt} loading="lazy"/></Link>)}<p className="platform-eyebrow">{map.focus}</p><h4>{preview?map.question:<Link to={'/maps/'+map.slug}>{map.question}</Link>}</h4><p>{map.takeaway}</p><p className="muted map-card-caution">{map.caution}</p><p className="map-update"><strong>{pick('本次变化：','This revision: ')}</strong>{map.change_summary}</p><p className="muted">{pick('主报告首次发布：','Report first released: ')}{map.reports[0]?.first_published_at} · {pick('地图修订：','Map revised: ')}{publicationTime(item.publication?.updated_at).slice(0,10)||pick('历史日期未记录','Historical date unavailable')}</p>{preview&&<><div id="map-overview"><MapGraph map={map} sources={item.sources}/></div><MapReportReading map={map} sources={item.sources}/></>}</article>;})}</div></section>;
}
const diffLabels:Record<string,[string,string]>={question:['技术问题','Question'],focus:['所属路线','Topic'],takeaway:['阅读要点','Takeaway'],caution:['适用边界','Caution'],change_summary:['修订说明','Change summary'],reports:['报告与日期','Reports and dates'],nodes:['节点与实验','Nodes and experiments'],edges:['关系与依据','Relationships and evidence'],sources:['原始出处','Sources'],related:['关联档案','Related dossiers'],reading:['报告阅读','Report reading']};
function DiffValue({field,value,map}:{field:string;value:unknown;map?:PublicMap}){
 const {pick}=useWorkspace();if(value==null)return <p>{pick('未收录','Not recorded')}</p>;if(typeof value==='string')return <p>{value}</p>;if(field==='reading')return <MapReportReading map={{...map!,reading:value as MapReading}} sources={map?.sources||[]} prefix={'diff-'+map?.revision+'-'}/>;if(!Array.isArray(value))return null;
 if(field==='nodes')return <>{(value as MapNode[]).map(n=><article key={n.id}><h4>{n.label}</h4><p>{n.mechanism}</p><p>{pick('条件：','Conditions: ')}{n.setting}</p><p>{pick('结果：','Result: ')}{n.result}</p><p>{pick('局限：','Limitations: ')}{n.limitation}</p>{n.metrics?.map((m,i)=><p key={i}>{m.label}：{m.value} {m.unit} · {m.baseline} · {m.conditions}</p>)}<Evidence points={n.evidence} sources={map?.sources||[]}/></article>)}</>;
 if(field==='edges')return <>{(value as TechnicalMap['edges']).map((e,i)=><article key={i}><h4>{map?.nodes.find(n=>n.id===e.from)?.label} → {map?.nodes.find(n=>n.id===e.to)?.label}</h4><p>{pick(relations[e.relation][0],relations[e.relation][1])} · {e.label}</p><Evidence points={e.evidence} sources={map?.sources||[]}/></article>)}</>;
 if(field==='reports')return <>{(value as TechnicalMap['reports']).map((r,i)=><article key={i}><p>{map?.sources.find(s=>s.id===r.source_id)?.title} · {r.version}</p><p>{pick('首次发布：','First published: ')}{r.first_published_at}{r.revised_at&&' · '+pick('报告修订：','Revised: ')+r.revised_at} · {r.revision_note}</p></article>)}</>;
 return <>{(value as {title?:string;name?:string;url:string}[]).map((s,i)=><p key={i}><SourceLink url={s.url}>{s.title||s.name}</SourceLink></p>)}</>;
}
function MapHistory({slug}:{slug:string}){
 const {pick}=useWorkspace();const history=useRemote<{items:{revision:number;recorded_at:string;date_basis:string;change_summary:string;object:PublicMap}[]}>('/v1/platform/maps/'+slug+'/history');const [from,setFrom]=useState(''),[to,setTo]=useState(''),[show,setShow]=useState(false);
 const compare=useRemote<{fields:{field:string;before:unknown;after:unknown}[]}>((show&&from&&to)?`/v1/platform/maps/${slug}/compare?from_revision=${from}&to_revision=${to}`:null);
 useEffect(()=>{const items=history.data?.items;if(items?.length){setTo(String(items[0].revision));setFrom(items[1]?String(items[1].revision):'');}},[history.data]);
 return <section className="map-history"><h2>{pick('修订记录','Revision history')}</h2>{history.error&&<p role="alert">{history.error}</p>}{history.data?.items.map(r=><details key={r.revision}><summary>{r.date_basis==='migration_baseline'?pick('导入基线','Imported baseline'):publicationTime(r.recorded_at)} · {r.change_summary}</summary><p className="muted">{r.date_basis==='migration_baseline'?pick('导入时间不代表首次发表时间。','Import time is not the original publication date.'):pick('已审公开修订','Reviewed public revision')}</p><div id={'history-'+r.revision+'-map-overview'}><MapGraph map={r.object} sources={r.object.sources} readingPrefix={'history-'+r.revision+'-'}/></div><MapReportReading map={r.object} sources={r.object.sources} prefix={'history-'+r.revision+'-'}/></details>)}{history.data?.items.length===1&&<p>{pick('目前只有一个已记录版本。后续审核发布会在此留下前后对照。','One recorded version. Future reviewed publications will add comparisons here.')}</p>}
 {(history.data?.items.length||0)>1&&<><div className="platform-actions">{[['from',from,setFrom],['to',to,setTo]].map(([key,v,set])=><label key={String(key)}>{pick(key==='from'?'较早版本':'较新版本',key==='from'?'Earlier':'Later')}<select value={String(v)} onChange={e=>{(set as typeof setFrom)(e.target.value);setShow(false);}}>{history.data?.items.map(r=><option key={r.revision} value={r.revision}>{r.date_basis==='migration_baseline'?pick('导入基线','Imported baseline'):publicationTime(r.recorded_at)} · {r.change_summary}</option>)}</select></label>)}<button className="button" disabled={!from||Number(from)>=Number(to)} onClick={()=>setShow(true)}>{pick('查看前后变化','Compare revisions')}</button></div>{show&&<>{compare.error&&<p role="alert">{compare.error}</p>}{compare.data?.fields.map(f=><details key={f.field} open><summary>{pick(...(diffLabels[f.field]||[f.field,f.field]))}</summary><div className="map-diff"><div><h3>{pick('之前','Before')}</h3><DiffValue field={f.field} value={f.before} map={history.data?.items.find(r=>r.revision===Number(from))?.object}/></div><div><h3>{pick('之后','After')}</h3><DiffValue field={f.field} value={f.after} map={history.data?.items.find(r=>r.revision===Number(to))?.object}/></div></div></details>)}</>}</>}
 </section>;
}
export function MapsPage(){const {slug}=useParams();return <MapPage key={slug||'index'} slug={slug}/>;}
function MapPage({slug}:{slug?:string}){
 const {pick,notify}=useWorkspace();const [highlightNode,setHighlightNode]=useState('');const [archive,setArchive]=useState('all'),[q,setQ]=useState(''),[copied,setCopied]=useState('');
 const data=useRemote<Maps>('/v1/platform/maps?'+(slug?'slug='+encodeURIComponent(slug):'archive='+archive+'&q='+encodeURIComponent(q)));const map=!data.loading&&!data.error?data.data?.items[0]:undefined;
 useEffect(()=>{setCopied('');},[slug]);
 useEffect(()=>{if(map&&window.location.hash){const id=decodeURIComponent(window.location.hash.slice(1));requestAnimationFrame(()=>document.getElementById(id)?.scrollIntoView());}},[map?.revision]);
 async function share(ai=false){if(!map)return;const text=ai?JSON.stringify({tool:'curated_maps',arguments:{slug:map.slug,revision:map.revision},map,instruction:'区分作者结果、实验条件和FieldToFit解读；保留单位、基线和原文位置，不能把不同资源比例相乘。'},null,2):new URL(map.path+window.location.hash,window.location.origin).href;setCopied(text);try{await navigator.clipboard.writeText(text);notify(pick('已复制','Copied'));}catch{notify(pick('可在下方选择并复制','Select and copy below'));}}
 return <div className="platform-page maps-page"><PageMetadata title={(slug?(map?.question||pick('技术地图','Technical map')):pick('技术报告精选&分析','Selected Technical Reports & Analysis'))+' · FieldToFit'} description={map?.takeaway||'精选原始报告，读懂核心结论、证据和适用边界'} path={slug?'/maps/'+slug:'/maps'} index={!data.loading&&!data.error}/><header className="platform-hero"><p className="platform-eyebrow">{pick('技术报告精选&分析','SELECTED TECHNICAL REPORTS & ANALYSIS')}</p><h1>{slug?(map?.question||pick('读取地图…','Loading map…')):pick('技术报告精选&分析','Selected Technical Reports & Analysis')}</h1><p>{slug?map?.focus:pick('近30日报告与实质修订单列；历史问题保留原入口，继续维护。','Recent reports and substantive revisions are distinct from historical topics, which retain stable links.')}</p>{slug&&map&&<p className="map-heading-dates">{pick('主报告：','Main report: ')}{map.reports[0]?.first_published_at} · {map.reports[0]?.version} · {pick('地图修订：','Map revised: ')}{publicationTime(map.publication?.updated_at)}</p>}<Link to="/for-you#technical-evolution-maps">← {pick('回到近期动态','Recent developments')}</Link></header>
 {data.loading&&<p role="status">{pick('正在读取…','Loading…')}</p>}{data.error&&<p role="alert">{data.error}</p>}
 {!slug&&<><div className="platform-actions"><label>{pick('地图范围','Scope')}<select value={archive} onChange={e=>setArchive(e.target.value)}><option value="all">{pick('全部问题','All topics')}</option><option value="recent">{pick('近期报告（30日）','Recent reports (30 days)')}</option><option value="historical">{pick('历史索引','Historical index')}</option></select></label><label>{pick('查找技术问题','Find a question')}<input type="search" value={q} onChange={e=>setQ(e.target.value)}/></label></div><div className="map-cards">{!data.loading&&!data.error&&data.data?.items.map(m=><article key={m.slug}>{mapThumbnail(m)&&<Link to={m.path} className="map-card-figure"><img width="778" height="447" src={mapThumbnail(m)!.image_url} alt={mapThumbnail(m)!.alt} loading="lazy"/></Link>}<p>{m.focus} · {m.archived?pick('历史问题','Historical topic'):pick('近期报告','Recent report')}</p><h2><Link to={m.path}>{m.question}</Link></h2><p>{m.takeaway}</p><p>{pick('本次变化：','This revision: ')}{m.change_summary}</p><p className="muted">{m.caution}</p><p className="muted">{pick('主报告：','Main report: ')}{m.reports[0]?.first_published_at} · {m.reports[0]?.version} · {pick('地图修订：','Map revised: ')}{publicationTime(m.publication?.updated_at)}</p></article>)}</div>{!data.loading&&!data.error&&data.data?.total===0&&<p>{pick('当前范围没有已审地图。','No reviewed maps in this scope.')}</p>}</>}
 {slug&&map&&!data.error&&<><p>{map.takeaway}</p><p className="map-caution">{map.caution}</p><div className="platform-actions"><button className="button" onClick={()=>share()}>{pick('复制地图链接','Copy link')}</button><button className="button" onClick={()=>share(true)}>{pick('把地图交给 AI','Give this map to AI')}</button></div>{copied&&<details><summary>{pick('展开已复制内容','Show copied content')}</summary><textarea aria-label={pick('地图分享内容','Map share content')} readOnly value={copied} rows={8}/></details>}
 <section id="map-overview" tabIndex={-1} className="map-overview"><h2>{pick('路线全貌','Route overview')}</h2><MapGraph key={map.revision} map={map} sources={map.sources} onSelect={setHighlightNode} selectedId={highlightNode}/></section><MapReportReading map={map} sources={map.sources} highlightNode={highlightNode} onRoute={setHighlightNode}/><section className="map-reports"><h2>{pick('报告与日期','Reports and dates')}</h2>{map.reports.map(r=><article key={r.source_id}><Evidence sources={map.sources} points={[{source_id:r.source_id,locator:r.version}]}/><p>{pick('首次发布：','First release: ')}{r.first_published_at}{r.revised_at&&' · '+pick('报告修订：','Report revision: ')+r.revised_at}{r.revision_note&&' · '+r.revision_note}</p></article>)}<p>{pick('地图首次发布：','Map first published: ')}{publicationTime(map.publication?.first_published_at)||pick('历史日期未留存','Historical date unavailable')} · {pick('地图最近修订：','Map last revised: ')}{publicationTime(map.publication?.updated_at)||pick('历史日期未留存','Historical date unavailable')}</p><p>{map.evidence_scope}</p></section>
 {!!map.related.length&&<section><h2>{pick('关联档案','Related dossiers')}</h2>{map.related.map(r=><p key={r.id}><Link to={'/watch/'+r.id}>{r.name}</Link></p>)}</section>}<MapHistory key={slug} slug={slug}/></>}
 </div>;
}
export function MapsAI(){const {pick}=useWorkspace();const data=useRemote<Maps>('/v1/platform/maps');return <section className="platform-panel" id="ai-technical-maps"><h2>{pick('技术报告精选&分析：带证据继续分析','Selected Technical Reports & Analysis: continue with evidence')}</h2><p>{pick('网页与 AI 读取同一份已审节点、关系、配置、单位和报告位置。选择地图后，可复制完整结构和读取参数。','The website and AI share reviewed nodes, relationships, configurations, units and report locations. Open a map to copy its structure and reading arguments.')}</p><code>curated_maps</code>{data.error&&<p role="alert">{data.error}</p>}{data.data?.items.map(m=><p key={m.slug}><Link to={m.path}>{m.question}</Link></p>)}<Link to="/maps">{pick('浏览精选与历史索引','Browse reports and history')} →</Link></section>;}

export function RelatedMaps({id}:{id:string}){const {pick}=useWorkspace();const data=useRemote<Maps>('/v1/platform/maps');const related=data.error?[]:data.data?.items.filter(m=>m.id===id||m.related.some(r=>r.id===id))||[];if(!related.length)return null;return <section className="platform-panel"><h2>{pick('相关报告分析','Related report analysis')}</h2>{related.map(m=><p key={m.slug}><Link to={m.path}>{m.question}</Link> · {m.focus}</p>)}</section>;}
