import type {TechnicalMap,MapEvidence} from './TechnicalMaps';
import './technical-maps.css';
type Source={id:string;title:string};
function Text({label,value,onChange,area=false,type='text'}:{label:string;value:unknown;onChange:(v:string)=>void;area?:boolean;type?:string}){return <label><span>{label}</span>{area?<textarea aria-label={label} value={String(value??'')} onChange={e=>onChange(e.target.value)}/>:<input aria-label={label} type={type} step={type==='number'?'any':undefined} value={String(value??'')} onChange={e=>onChange(e.target.value)}/>}</label>;}
function SourceChoice({value,sources,onChange}:{value:string;sources:Source[];onChange:(v:string)=>void}){return <label>依据来自<select aria-label="依据来自" value={value} onChange={e=>onChange(e.target.value)}><option value="">选择已登记的来源</option>{sources.map(s=><option key={s.id} value={s.id}>{s.title||s.id}</option>)}</select></label>;}
function EvidenceEditor({value,sources,onChange}:{value:MapEvidence[];sources:Source[];onChange:(v:MapEvidence[])=>void}){return <div>{value.map((e,i)=><fieldset key={i}><legend>原文依据 {i+1}</legend><SourceChoice value={e.source_id} sources={sources} onChange={v=>onChange(value.map((x,j)=>j===i?{...x,source_id:v}:x))}/><Text label="原文位置（节／页）" value={e.locator} onChange={v=>onChange(value.map((x,j)=>j===i?{...x,locator:v}:x))}/><Text label="网页定位（网址 # 后的部分，可留空）" value={e.fragment} onChange={v=>onChange(value.map((x,j)=>j===i?{...x,fragment:v}:x))}/><button type="button" className="text-button" onClick={()=>onChange(value.filter((_,j)=>j!==i))}>移除此依据</button></fieldset>)}<button type="button" className="button" onClick={()=>onChange([...value,{source_id:sources[0]?.id||'',locator:'',fragment:''}])}>添加原文依据</button></div>;}
export function TechnicalMapEditor({value,onChange,onPending,sources=[]}:{value?:TechnicalMap|null;onChange:(v:TechnicalMap|null)=>void;onPending:(key:string,v:boolean)=>void;sources?:Source[]}){
 const update=(key:string,v:unknown)=>onChange({...value!,[key]:v});const field=(key:keyof TechnicalMap,label:string,area=false)=><Text key={key} label={label} area={area} value={value?.[key]} onChange={v=>update(key,v)}/>;
 return <details className="map-editor" open={!!value}><summary>技术演化地图（按问题长期整理）</summary><label><input type="checkbox" checked={!!value} onChange={e=>{onPending('map-reports',false);onPending('map-edges',false);onChange(e.target.checked?{slug:'',question:'',focus:'',takeaway:'',caution:'',change_summary:'',reports:[],nodes:[],edges:[]}:null);}}/>作为技术地图展示</label>{value&&<><p>公开入口建立后沿用原地址。每个方法和关系须有原始报告位置；数值保留单位、比较对象与条件。</p>{field('slug','稳定入口（如 agent-context-cost）')}{field('question','技术问题')}{field('focus','所属路线')}{field('takeaway','读者能获得什么',true)}{field('caution','结果适用边界',true)}{field('change_summary','本次公开修订说明',true)}
 <h4>原始报告与日期</h4>{value.reports.map((r,i)=><fieldset key={i}><legend>报告 {i+1}</legend><SourceChoice value={r.source_id} sources={sources} onChange={v=>update('reports',value.reports.map((x,j)=>j===i?{...x,source_id:v}:x))}/>{([['version','报告版本','text'],['first_published_at','报告首次发布','date'],['revised_at','报告修订日期（没有则留空）','date'],['revision_note','本次报告新增方法、实验或更正','text']] as const).map(([k,l,t])=><Text key={k} label={l} type={t} value={r[k]} onChange={v=>update('reports',value.reports.map((x,j)=>j===i?{...x,[k]:k==='revised_at'?(v||null):v}:x))}/>)}<label><input type="checkbox" checked={r.substantive_revision} onChange={e=>update('reports',value.reports.map((x,j)=>j===i?{...x,substantive_revision:e.target.checked}:x))}/>这是实质修订，包含方法、实验或事实更正</label><button type="button" className="text-button" onClick={()=>update('reports',value.reports.filter((_,j)=>j!==i))}>移除此报告</button></fieldset>)}<button className="button" type="button" onClick={()=>update('reports',[...value.reports,{source_id:sources[0]?.id||'',version:'',first_published_at:'',revised_at:null,substantive_revision:false,revision_note:''}])}>添加报告</button>
 <h4>节点与实验</h4>{value.nodes.map((n,i)=><fieldset key={n.id}><legend>节点 {i+1} · {n.label}</legend><div className="map-editor-row"><label>节点类型<select aria-label="节点类型" value={n.kind} onChange={e=>update('nodes',value.nodes.map((x,j)=>j===i?{...x,kind:e.target.value}:x))}><option value="baseline">比较基线</option><option value="method">方法</option><option value="result">组合结果</option></select></label><label>地图位置<select aria-label="地图位置" value={n.stage} onChange={e=>update('nodes',value.nodes.map((x,j)=>j===i?{...x,stage:Number(e.target.value)}:x))}>{Array.from({length:9},(_,k)=><option value={k} key={k}>{k===0?'起点':k===1?'第一列方法':k===2?'结果／后续方法':'后续第'+k+'列'}</option>)}</select></label></div>{([['label','名称'],['mechanism','机制'],['setting','条件／配置'],['result','报告结果'],['limitation','局限']] as const).map(([k,l])=><Text key={k} label={l} area value={n[k]} onChange={v=>update('nodes',value.nodes.map((x,j)=>j===i?{...x,[k]:v}:x))}/>)}<EvidenceEditor sources={sources} value={n.evidence} onChange={v=>update('nodes',value.nodes.map((x,j)=>j===i?{...x,evidence:v}:x))}/>
 {(n.metrics||[]).map((m,k)=><fieldset key={k}><legend>数值指标 {k+1}</legend>{([['label','指标名称'],['value','报告数值'],['unit','单位'],['baseline','比较对象／基线'],['conditions','比较条件']] as const).map(([key,l])=><Text key={key} label={l} type={key==='value'?'number':'text'} value={m[key]} onChange={v=>update('nodes',value.nodes.map((x,j)=>j===i?{...x,metrics:(x.metrics||[]).map((y,z)=>z===k?{...y,[key]:key==='value'?(v===''?null:Number(v)):v}:y)}:x))}/>)}<button type="button" className="text-button" onClick={()=>update('nodes',value.nodes.map((x,j)=>j===i?{...x,metrics:(x.metrics||[]).filter((_,z)=>z!==k)}:x))}>移除此指标</button></fieldset>)}<button type="button" className="button" onClick={()=>update('nodes',value.nodes.map((x,j)=>j===i?{...x,metrics:[...(x.metrics||[]),{label:'',value:null,unit:'',baseline:'',conditions:''}]}:x))}>添加数值指标</button><button type="button" className="text-button" onClick={()=>onChange({...value,nodes:value.nodes.filter((_,j)=>j!==i),edges:value.edges.filter(e=>e.from!==n.id&&e.to!==n.id)})}>移除此节点及其关系</button></fieldset>)}<button type="button" className="button" onClick={()=>update('nodes',[...value.nodes,{id:'node-'+crypto.randomUUID().slice(0,8),kind:'method',stage:1,label:'',mechanism:'',setting:'',result:'',limitation:'',evidence:[],metrics:[]}])}>添加节点</button>
 <h4>关系与依据</h4>{value.edges.map((e,i)=><fieldset key={i}><legend>关系 {i+1}</legend>{(['from','to'] as const).map(k=><label key={k}>{k==='from'?'起点节点':'终点节点'}<select aria-label={k==='from'?'起点节点':'终点节点'} value={e[k]} onChange={v=>update('edges',value.edges.map((x,j)=>j===i?{...x,[k]:v.target.value}:x))}>{value.nodes.map(n=><option value={n.id} key={n.id}>{n.label||'未命名节点'}</option>)}</select></label>)}<label>关系含义<select aria-label="关系含义" value={e.relation} onChange={v=>update('edges',value.edges.map((x,j)=>j===i?{...x,relation:v.target.value}:x))}><option value="inheritance">方法继承／纳入</option><option value="baseline">基线比较</option><option value="parallel">并行探索</option></select></label><Text label="这条关系说明什么" value={e.label} onChange={v=>update('edges',value.edges.map((x,j)=>j===i?{...x,label:v}:x))}/><EvidenceEditor value={e.evidence} sources={sources} onChange={v=>update('edges',value.edges.map((x,j)=>j===i?{...x,evidence:v}:x))}/><button type="button" className="text-button" onClick={()=>update('edges',value.edges.filter((_,j)=>j!==i))}>移除此关系</button></fieldset>)}<button type="button" className="button" onClick={()=>update('edges',[...value.edges,{from:value.nodes[0]?.id||'',to:value.nodes[1]?.id||'',relation:'inheritance',label:'',evidence:[]}])}>添加关系</button>
 </>}</details>;
}
