import { useEffect, useState, type FormEvent } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { useRemote } from '../api/knowledge';
import { SourceLink, useWorkspace } from '../components/workspace/UI';
import { WatchHandoff, type WatchCollection, watchAnchor } from '../components/workspace/ContinuousWatch';

const repo='https://github.com/Kevinxnova/FieldToFit';
const labels=['项目名称','项目介绍（解决的问题、面向的人）','项目入口','如何使用','开放情况','作者与提交者关系'];
const template=labels.map(s=>`${s}：\n`).join('\n');
export function Community(){
 const {pick,notify}=useWorkspace();
 const location=useLocation();
 useEffect(()=>{if(location.hash==='#submit-project'){const frame=requestAnimationFrame(()=>{const el=document.getElementById('submit-project');el?.focus({preventScroll:true});el?.scrollIntoView();});return()=>cancelAnimationFrame(frame);}},[location.hash]);
 const [values,setValues]=useState(['','','','','','']);const [fallback,setFallback]=useState(false);const [draft,setDraft]=useState('');
 const body=values.map((v,i)=>`${labels[i]}：\n${v.trim()}`).join('\n\n');
 const subject='项目投稿｜'+values[0].trim();
 const issue=repo+'/issues/new?'+new URLSearchParams({title:subject,body});
 const mail='mailto:fieldtofit@163.com?'+new URLSearchParams({subject,body}).toString().replace(/\+/g,'%20');
 async function copy(value:string){try{await navigator.clipboard.writeText(value);notify(pick('已复制，请检查后发送','Copied; review before sending'));}catch{setDraft(value);setFallback(true);}}
 function prepare(e:FormEvent){e.preventDefault();if(values.some(v=>!v.trim())){notify(pick('请完整填写六项信息','Complete all six fields'));return;}setDraft(body);setFallback(false);}
 return <div className="platform-page community-page"><header className="platform-hero"><p className="platform-eyebrow">FIELDTOFIT COMMUNITY</p><h1>{pick('FieldToFit 社区','FieldToFit Community')}</h1><p className="platform-lead">{pick('FieldToFit 计划逐步建立一个围绕 AI 应用的共建社区，建设持续更新、可追溯、人与 AI 都能使用的 AI 应用资料库（AI Application Database）。','FieldToFit plans to build a community around AI applications: a continuously maintained, traceable AI Application Database for people and AI.')}</p><p>{pick('我们希望把值得关注的模型、工具、开发经验和开发者投稿项目整理下来，让已有成果更容易被发现、理解和采用。','We want to organize noteworthy models, tools, development experience and developer-submitted projects so existing work is easier to discover, understand and adopt.')}</p><p>{pick('无论你正在开发项目、研究一种方法，还是愿意补充资料、测试工具、完善文档，都可以参与。让做的事情让更多人看见，让更多人一起参与开发。欢迎加入共建，一起做出有意义的事情！','Whether you develop projects, research methods, contribute materials, test tools or improve documentation, you can take part. Help more people discover the work and join development. Build something meaningful together!')}</p></header>
 <section className="platform-panel"><h2>{pick('参与共建','Take part')}</h2><div className="community-grid"><a className="community-action" href="#submit-project"><strong>{pick('提交个人开发项目','Submit your project')}</strong><span>{pick('介绍你的成果，寻找使用者和开发伙伴。','Share your work and find users and collaborators.')} →</span></a><Link className="community-action" to="/feedback?category=missing"><strong>{pick('推荐资源或纠错','Recommend or correct')}</strong><span>{pick('补充值得关注的资料，帮助内容保持准确。','Recommend materials and improve accuracy.')} →</span></Link><a className="community-action" href={repo+'/blob/codex/fieldtofit-knowledge-workspace/CONTRIBUTING.md'} target="_blank" rel="noopener noreferrer"><strong>{pick('参与 FieldToFit 开发','Contribute development')}</strong><span>{pick('从资料整理、测试、文档或功能开发开始。','Start with curation, tests, documentation or features.')} ↗</span></a></div></section>
 <section className="platform-panel" aria-labelledby="submit-project"><p className="platform-eyebrow">DEVELOPER SUBMISSIONS</p><h2 id="submit-project" tabIndex={-1}>{pick('开发者投稿项目','Developer-submitted projects')}</h2><h3>{pick('让你的项目，被更多人看见。','Let more people discover your project.')}</h3><p>{pick('FieldToFit 将持续收录高质量的个人和团队开发的 AI 应用、工具与开源项目。只要已经有可以查看的原型、演示或代码，并能说明它解决什么问题，就可以提交。','FieldToFit will collect high-quality AI applications, tools and open-source projects from individuals and teams. Submit a viewable prototype, demo or code with a clear explanation of the problem it solves.')}</p><p>{pick('我们会整理项目用途、使用方式、当前进展和协作需求，让读者更容易了解、尝试，也让他们的 AI 能找到相关资料。','We organize purpose, usage, progress and collaboration needs so readers can understand and try projects, and their AI can find the materials.')}</p><p>{pick('如果你正在寻找测试者、开发伙伴，或需要有人一起完善文档与功能，也欢迎在项目中明确写出来。','If you need testers, collaborators, documentation or feature contributors, include that in your introduction.')}</p>
 <p className="muted">{pick('不设 Star 门槛；有实际成果、介绍清楚、入口可核对即可投稿。GitHub 投稿公开；邮件只整理确认后的项目信息，不公开邮件本身。','No star threshold: provide real work, a clear introduction and a verifiable entry. GitHub submissions are public; emails are not published, only confirmed project information.')}</p>
 <form className="community-form" onSubmit={prepare} onChange={()=>setDraft('')}><div className="community-form-grid">{labels.map((label,i)=><label key={label}>{pick(label,['Project name','Introduction (problem and audience)','Project URL','How to use','Open-source status','Your relationship to the author'][i])}{i>=4?<select required value={values[i]} onChange={e=>setValues(v=>v.map((x,j)=>j===i?e.target.value:x))}><option value="">{pick('请选择','Select')}</option>{(i===4?['开源','部分开源','闭源']:['本人开发','团队成员','第三方推荐']).map((v,j)=><option key={v} value={v}>{pick(v,(i===4?['Open source','Partially open source','Closed source']:['Author','Team member','Third-party recommendation'])[j])}</option>)}</select> : i===0||i===2?<input required type={i===2?'url':'text'} maxLength={i===0?60:300} value={values[i]} onChange={e=>setValues(v=>v.map((x,j)=>j===i?e.target.value:x))} placeholder={i===2?'https://…':undefined} pattern={i===2?'https?://.+':'.*\\S.*'}/>:<textarea required maxLength={240} rows={3} value={values[i]} onChange={e=>setValues(v=>v.map((x,j)=>j===i?e.target.value:x))}/>}</label>)}</div><button className="button primary">{pick('生成投稿内容','Prepare submission')}</button></form>
 {draft&&!fallback&&<div className="community-draft" aria-live="polite"><h3>{pick('检查内容，再选择发送方式','Review, then choose a channel')}</h3><pre>{draft}</pre><div className="platform-actions"><a className="button primary" href={issue} target="_blank" rel="noopener noreferrer">{pick('通过 GitHub 提交','Submit via GitHub')}</a><a className="button" href={mail}>{pick('通过邮箱提交','Submit by email')}</a><button className="text-button" onClick={()=>copy(draft)}>{pick('复制投稿内容','Copy submission')}</button></div><p className="muted">{pick('这里仅生成草稿；请在 GitHub 或邮件客户端确认发送。若邮件内容未完整带入，可复制后粘贴。','This prepares a draft only. Confirm sending in GitHub or your email client. If your email client omits content, copy and paste it.')}</p></div>}
 <div className="platform-actions"><button className="text-button" onClick={()=>copy(template)}>{pick('复制空白投稿模板','Copy blank template')}</button><a href="mailto:fieldtofit@163.com">fieldtofit@163.com</a></div>{fallback&&<textarea className="community-copy-fallback" aria-label={pick('可手动复制的投稿内容','Submission text to copy')} readOnly value={draft} rows={12}/>}
 </section><section className="platform-panel"><h2>{pick('提交后会发生什么','After submission')}</h2><ol className="community-process">{[pick('收到投稿并核对项目入口与信息。','Review the submission and project entry.'),pick('必要时联系补充材料，整理发布内容并确认。','Request missing materials and confirm the prepared profile.'),pick('审核通过后收录，保留作者关系、出处、核验日期和未知项。','Publish after review, preserving attribution, sources, dates and unknowns.'),pick('后续在原 Issue 补充，或通过邮件说明项目名称和更新内容。','Update the original issue or email the project name and changes.')].map(s=><li key={s}>{s}</li>)}</ol><p>{pick('每周集中处理投稿；提交不等于自动收录。已收录项目有变化时，经核对再更新。','Submissions are reviewed weekly, not automatically published. Updates to listed projects are reviewed before publication.')}</p></section><DeveloperProjects/></div>;
}

export function DeveloperProjects({ai=false}:{ai?:boolean}){
 const {pick}=useWorkspace();const result=useRemote<WatchCollection>('/v1/platform/watch?origin=developer_submission');
 return <section className="platform-panel developer-projects"><h2 id="developer-projects" tabIndex={-1}>{pick('开发者投稿项目','Developer-submitted projects')}</h2>{result.loading?<p role="status">{pick('正在读取投稿项目…','Loading projects…')}</p>:result.error?<><p role="alert">{pick('投稿项目暂时无法读取。','Projects are temporarily unavailable.')}</p><button className="button" onClick={result.reload}>{pick('重试','Retry')}</button></>:result.data?.items.length?<><p>{pick('以下项目已审核收录，介绍与原始材料分开保留。','Reviewed submissions with summaries and original references kept distinct.')}</p>{result.data.items.map(item=><article key={item.id} className="developer-project-card"><h3><Link to={'/for-you#'+watchAnchor(item.id)}>{item.name}</Link></h3><p>{item.introduction}</p>{item.submission&&<dl><dt>{pick('项目入口','Project')}</dt><dd><SourceLink url={item.submission.entry_url}>{pick('访问项目','Open project')}</SourceLink></dd><dt>{pick('如何使用','Usage')}</dt><dd>{item.submission.usage}</dd><dt>{pick('开放情况','Openness')}</dt><dd>{item.submission.openness}</dd><dt>{pick('作者与提交者关系','Relationship')}</dt><dd>{item.submission.relationship}</dd></dl>}<p>{pick('核验日期：','Reviewed: ')}{item.checked_at}</p><WatchHandoff data={result.data!} item={item}/></article>)}<WatchHandoff data={result.data}/></>:<p>{pick('暂时没有已审核收录的投稿项目。欢迎提交真实项目，审核后会在这里展示。','No reviewed developer submissions yet. Submit a real project to be considered for publication here.')}</p>}{ai&&<p>{pick('接入后可用 curated_watch，参数 origin: developer_submission 读取同源投稿资料；当前没有收录时返回空列表。','Read these same profiles with curated_watch and origin: developer_submission; it returns an empty list when no submissions are published.')}</p>}<Link className="button" to="/community#submit-project">{pick('提交个人开发项目','Submit your project')}</Link></section>;
}
